from django.contrib import admin
from django.urls import path

from . import views 

urlpatterns = [
    path('',views.home),
    path('login/',views.login),
    path('user/',views.user),
    path('adminhome/',views.admin_home),
    path('products/',views.product),
    path('shopreg/',views.shopreg),
    path('viewcustomer/',views.viewcustomer),  
    path('type/',views.type),
    path('viewstocks/',views.viewstock),
    path('viewshop/',views.viewshop),
    path('accepted/<id>',views.saccepted),
    path('adb/<id>',views.adb),
    path('rejected/<id>',views.srejected),
    path('delivery/',views.delivery),
    path('viewcomplaint/',views.view_complaints),
    path('stype/',views.stype),
    path('shome/',views.shopehome),
    path('manage/',views.sproducts),
    path('deletep/<id>',views.deletepr),
    path('editt/<id>',views.editt),
    path('vieworder/',views.orders),
    path('oaccepted/<id>',views.oaccepted),
    path('adb/<id>/<o>',views.adb),
    path('orejected/<id>',views.orejected),
    path('viewpayments/',views.viewpayments),
    path('viewrating/',views.viewrating),
    path('deliveryboyhome/',views.deliveryhome),
    path('orderass/',views.viewassignorder),
    path('vieworderpickup/',views.pickeduporder),
    path('update/<int:id>/',views.update_delivery),
    path('userhome/',views.userhome),
    path('shop1/',views.shops),
    path('shop/<int:shop_id>/view_products/',views.productss),
  
    path('chatuse/<sid>',views.userchat),
    path('chatsho/<uid>',views.shopchat),

 
    path('cart/<int:pid>/<price>',views.addtocart),
    path('rating1/',views.sortbyrating),
    path('category/',views.category),
    path('productdetails/',views.productdetails),
    path('viewcart/',views.viewcart),
    path('makepay/<id>',views.makepayment),
    path('userpayment/<id>',views.userpay),
    path('choose/',views.choosedelivery),
    path('my_orders/',views.my_orders),
    path('addrating/<id>',views.add_rating),
    path('order_history/',views.order_history),
    path('view_reply/', views.view_reply),
    path('saccepted/<id>',views.saccepted),
    path('edite/<pid>',views.edited),
    path('deletet/<id>',views.deletet),
    path('dedit/<id>',views.dedit),
    path('ddelete/<id>',views.ddelete),
    path('verified/<id>',views.verified),
    path('view_product/<id>',views.productss),
    path('pickedup/<id>',views.picke),
    path('delivered/<id>',views.deliveryed),
    path('send_complaint/',views.send_complaint),
    path('logout/',views.logout1),
    path('logout1/',views.logout2),
    path('logout3/',views.logout3),
    path('logout4/',views.logout4),
    path('rating/<id>',views.rating),
    path('rate1/',views.rate),

]