# Generated by Django 4.1 on 2025-07-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender_type', models.CharField(max_length=100)),
                ('receiver_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.login')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.login')),
            ],
        ),
        migrations.CreateModel(
            name='SetToDeliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.deliveryboy')),
                ('order_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.ordermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.type'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('order_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.ordermaster')),
            ],
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.shop'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.user'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.ordermaster')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.product')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.login'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.deliveryboy')),
                ('order_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.ordermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.user')),
            ],
        ),
    ]
